site_name: CPP-GL Documentation
site_description: "General-purpose Template Graph and Hypergraph Library for Modern C++"
repo_url: "https://github.com/SpectraL519/cpp-gl"

nav:
  - Home: index.md
  - GL:
      - Overview: cpp-gl/group__gl.md
      - Algorithms: cpp-gl/group__gl__alg.md
  - HGL:
      - Overview: cpp-gl/group__hgl.md
      - Algorithms: cpp-gl/group__hgl__alg.md
  - Full API Index:
      - Namespaces: cpp-gl/namespaces.md
      - Classes & Structs: cpp-gl/annotated.md
      - Files: cpp-gl/files.md

theme:
  name: material
  logo: img/cpp-gl-hex.png
  favicon: img/cpp-gl-hex.png
  # icon:
  #   logo: material/graph
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-5
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-3
        name: Switch to light mode

markdown_extensions:
  - admonition
  - tables
  - md_in_html
  - attr_list
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets:
      base_path: "."
      check_paths: true

plugins:
  - search
  - include-markdown
  - callouts:
      aliases: false
  - mkdoxy:
      projects:
        cpp-gl:
          src-dirs: "include docs/groups.dox"
          full-doc: True
          doxy-cfg:
            PROJECT_NAME: "CPP-GL"
            EXTRACT_ALL: False
            HIDE_UNDOC_MEMBERS: True
            HIDE_UNDOC_CLASSES: True
            EXTRACT_STATIC: False

extra_javascript:
  - scripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - style/logo.css
  - style/theme.css
