site_name: CPP-GL Documentation
site_description: "General-purpose Template Graph and Hypergraph Library for Modern C++"
repo_url: "https://github.com/SpectraL519/cpp-gl"

nav:
  - Home: index.md
  - GL:
      # TODO: Tutorial page
      - Overview: cpp-gl/group__GL.md
      - Core Graph Components: cpp-gl/group__GL-Core.md
      - Graph Algorithms: cpp-gl/group__GL-Algorithm.md
      - Graph Topologies: cpp-gl/group__GL-Topology.md
      - I/O Utility: cpp-gl/group__GL-IO.md
      - Traits & Concepts: cpp-gl/group__GL-Traits.md
      - Generic Types: cpp-gl/group__GL-Types.md
      - General Utilities: cpp-gl/group__GL-Util.md
  # - HGL:
  #     - Overview: cpp-gl/group__hgl.md
  #     - Algorithms: cpp-gl/group__hgl__alg.md
  - API Index:
      - Modules: cpp-gl/modules.md
      - Namespaces: cpp-gl/namespaces.md
      - Classes & Structs: cpp-gl/annotated.md
      - Class Hierarchy: cpp-gl/hierarchy.md
      - Traits & Concepts: cpp-gl/concepts.md
      - Files: cpp-gl/files.md
      - Todo List: cpp-gl/todo.md
      # - Bug List: cpp-gl/bug.md
      # - Deprecated: cpp-gl/deprecated.md

theme:
  name: material
  logo: img/cpp-gl-hex.png
  favicon: img/cpp-gl-hex.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - content.code.copy
    - content.code.select
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-5
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-3
        name: Switch to light mode

markdown_extensions:
  - admonition
  - tables
  - md_in_html
  - attr_list
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets:
      base_path: "."
      check_paths: true
  - toc:
      toc_depth: 2

plugins:
  - search
  - include-markdown
  - callouts:
      aliases: false
  - mkdoxy:
      projects:
        cpp-gl:
          src-dirs: "include docs/groups.dox"
          full-doc: true
          doxy-cfg:
            PROJECT_NAME: "CPP-GL"
            MARKDOWN_SUPPORT: "YES"
            EXTRACT_ALL: "NO"
            HIDE_UNDOC_MEMBERS: "YES"
            HIDE_UNDOC_CLASSES: "YES"
            EXTRACT_STATIC: "NO"
            EXTRACT_PRIVATE: "NO"
            INTERNAL_DOCS: "NO"
            EXCLUDE_SYMBOLS: "std doctest doctest_detail_test_suite_ns detail *::detail"
            ENABLE_PREPROCESSING: "YES"
            MACRO_EXPANSION: "YES"
            EXPAND_ONLY_PREDEF: "YES"
            PREDEFINED: "gl_attr_force_inline="

extra_javascript:
  - scripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - style/logo.css
  - style/theme.css

extra:
  version:
    provider: mike
    default: "latest"
