import os
import xml.etree.ElementTree as ET
import argparse
import re

# =============================================================================
# CONFIGURATION
# =============================================================================
GROUPS = {
    "GL": {
        "prefix": "gl::",
        "filename": "gl_traits.md",
        "anchor": "gl-traits-concepts-documentation",
        "title": "GL Traits & Concepts",
        "description": "This page documents the C++20 concepts and type traits used to constrain templates across the GL library."
    },
    "HGL": {
        "prefix": "hgl::",
        "filename": "hgl_traits.md",
        "anchor": "hgl-traits-concepts-documentation",
        "title": "HGL Traits & Concepts",
        "description": "This page documents the C++20 concepts and type traits used to constrain templates across the HGL library."
    }
}

WARNING_BANNER = """> [!IMPORTANT]
> This page is automatically generated by `generate_concepts.py` to bridge the gap in MkDoxy's C++20 concept support. **Do not edit this file manually.**
"""

GLOBAL_CONCEPT_LINKS = {}

def get_text(element):
    """Extracts raw text from an XML element, stripping all tags. (Used for pure C++ blocks)"""
    if element is None:
        return ""
    return "".join(element.itertext()).strip()

def xml_to_md(elem):
    """Recursively converts Doxygen XML text nodes to Markdown links and formatting."""
    if elem is None:
        return ""

    res = elem.text or ""
    for child in elem:
        if child.tag == 'ref':
            ref_text = "".join(child.itertext())
            refid = child.get('refid', '')

            # 1. Known Concepts: Link exactly to their file and anchor
            if refid in GLOBAL_CONCEPT_LINKS:
                res += f"[`{ref_text}`]({GLOBAL_CONCEPT_LINKS[refid]})"

            # 2. External/Unknown Concepts (Fallback)
            elif refid.startswith('concept'):
                ref_anchor = ref_text.replace("::", "-").replace("_", "-")
                res += f"[`{ref_text}`](#{ref_anchor})"

            # 3. Classes, Structs, Namespaces (Fix: MkDoxy generates flat files!)
            elif refid.startswith('class') or refid.startswith('struct') or refid.startswith('namespace'):
                res += f"[`{ref_text}`]({refid}.md)"

            # 4. Unknown type (Degrade gracefully to code font)
            else:
                res += f"`{ref_text}`"

        elif child.tag in ['computeroutput', 'preformatted']:
            res += f"`{xml_to_md(child)}`"
        elif child.tag == 'bold':
            res += f"**{xml_to_md(child)}**"
        elif child.tag == 'emphasis':
            res += f"*{xml_to_md(child)}*"
        elif child.tag == 'itemizedlist':
            res += "\n"
            for item in child.findall('listitem'):
                res += f"- {xml_to_md(item).strip()}\n"
            res += "\n"
        else:
            res += xml_to_md(child)

        res += child.tail or ""

    return res

def parse_concept_xml(xml_path):
    """Parses a single Doxygen concept XML file."""
    tree = ET.parse(xml_path)
    root = tree.find('compounddef')

    if root is None or root.get('kind') != 'concept':
        return None

    name = root.findtext('compoundname')
    anchor = name.replace("::", "-").replace("_", "-")

    # Extract descriptions using the Markdown-aware parser
    brief = xml_to_md(root.find('briefdescription')).strip()

    details = ""
    params = []

    detailed_desc = root.find('detaileddescription')
    if detailed_desc is not None:
        for para in detailed_desc.findall('para'):
            param_list = para.find('.//parameterlist[@kind="templateparam"]')
            if param_list is not None:
                for item in param_list.findall('parameteritem'):
                    p_name = xml_to_md(item.find('.//parametername')).strip()
                    p_desc = xml_to_md(item.find('.//parameterdescription')).strip()
                    params.append({"name": p_name, "desc": p_desc})
                para.remove(param_list) # Remove so it isn't rendered twice

            para_text = xml_to_md(para).strip()
            if para_text:
                details += para_text + "\n\n"

    # Safely extract definition using strict get_text (NO Markdown allowed)
    constraint = get_text(root.find('initializer')).strip()

    # Fix Doxygen's weird spacing injections (e.g. '=  c_properties')
    constraint = re.sub(r'=\s+', '= ', constraint)

    # Check if Doxygen already included the 'template <...>' keyword
    if constraint.startswith("template"):
        definition = constraint
        if not definition.endswith(";"):
            definition += ";"
    else:
        # Fallback for older Doxygen versions
        template_decl = "template <"
        tpl_nodes = root.findall('.//templateparamlist/param')
        tpl_strings = [get_text(p.find('type')).strip() for p in tpl_nodes]
        template_decl += ", ".join(tpl_strings) + ">\n"
        definition = f"{template_decl}concept {name.split('::')[-1]} = {constraint};"

    return {
        "name": name,
        "anchor": anchor,
        "brief": brief,
        "details": details.strip(),
        "params": params,
        "definition": definition
    }

def generate_group_markdown(group_info, concepts):
    """Generates the Markdown file for a specific group."""
    md = f"# {group_info['title']} {{: #{group_info['anchor']} }}\n\n"
    md += f"{group_info['description']}\n\n{WARNING_BANNER}\n---\n\n"

    if not concepts:
        md += "*No concepts are currently documented for this module.*\n"
        return md

    for c in concepts:
        md += f"## `{c['name']}` {{: #{c['anchor']} }}\n\n"
        if c['brief']:
            md += f"{c['brief']}\n\n"
        if c['details']:
            md += f"### Detailed Description\n\n{c['details']}\n\n"
        if c['params']:
            md += "### Template Parameters\n\n| Parameter | Description |\n| :--- | :--- |\n"
            for p in c['params']:
                md += f"| `{p['name']}` | {p['desc']} |\n"
            md += "\n"

        md += f"### Definition\n\n```cpp\n{c['definition']}\n```\n\n---\n\n"
    return md

def generate_index_markdown(groups_data):
    """Generates the central API index mapping to all grouped concepts."""
    md = "# Concepts API Reference {: #concepts-api-reference }\n\n"
    md += "This page serves as the central index for all C++20 concepts used across the library to enforce type safety and template constraints.\n\n"
    md += f"{WARNING_BANNER}\n---\n\n"

    for group_key, group_info in GROUPS.items():
        md += f"## {group_key} Concepts\n\n"
        md += f"- **[{group_info['title']}]({group_info['filename']})**: Full API reference.\n"

        concepts = groups_data.get(group_key, [])
        if not concepts:
            md += f"    - *(Documentation coming soon)*\n"
        else:
            for c in concepts:
                desc_text = f": {c['brief']}" if c['brief'] else ""
                md += f"    - [`{c['name']}`]({group_info['filename']}#{c['anchor']}){desc_text}\n"
        md += "\n---\n\n"
    return md

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--xml", default="xml", help="Path to Doxygen XML output")
    parser.add_argument("--out", default="docs/cpp-gl", help="Path to MkDocs output folder")
    args = parser.parse_args()

    index_xml = os.path.join(args.xml, "index.xml")
    if not os.path.exists(index_xml):
        print(f"Error: Could not find Doxygen index at {index_xml}. Run Doxygen first.")
        return

    tree = ET.parse(index_xml)
    categorized_concepts = {key: [] for key in GROUPS.keys()}

    # PASS 1: Build the Global Concept Dictionary for Cross-Linking
    for compound in tree.findall("compound[@kind='concept']"):
        name = compound.findtext('name')
        if not name:
            continue
        refid = compound.get("refid")
        anchor = name.replace("::", "-").replace("_", "-")

        for group_key, group_info in GROUPS.items():
            if name.startswith(group_info["prefix"]):
                GLOBAL_CONCEPT_LINKS[refid] = f"{group_info['filename']}#{anchor}"
                break

    # PASS 2: Parse and format the XML
    for compound in tree.findall("compound[@kind='concept']"):
        xml_path = os.path.join(args.xml, f"{compound.get('refid')}.xml")
        if os.path.exists(xml_path):
            data = parse_concept_xml(xml_path)
            if data:
                for group_key, group_info in GROUPS.items():
                    if data["name"].startswith(group_info["prefix"]):
                        categorized_concepts[group_key].append(data)
                        break

    # PASS 3: Sort alphabetically and write files
    os.makedirs(args.out, exist_ok=True)

    for group_key, group_info in GROUPS.items():
        categorized_concepts[group_key].sort(key=lambda x: x['name'])
        out_path = os.path.join(args.out, group_info['filename'])
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(generate_group_markdown(group_info, categorized_concepts[group_key]))
        print(f"Generated {out_path} ({len(categorized_concepts[group_key])} concepts)")

    index_path = os.path.join(args.out, "concepts.md")
    with open(index_path, "w", encoding="utf-8") as f:
        f.write(generate_index_markdown(categorized_concepts))
    print(f"Generated {index_path} (API Index)")

if __name__ == "__main__":
    main()
