name: Benchmarks Smoke Test
on:
  push:
    branches:
      - "*"
    paths:
      - .github/workflows/benchmarks.yaml
      - CMakeLists.txt
      - cmake/
      - include/**
      - benchmarks/**

jobs:
  build:
    name: Build and Run Benchmarks (Smoke Test)
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies (Boost)
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-graph-dev

      - name: Prepare
        env:
          CC: gcc-14
          CXX: g++-14
        run: |
          cmake -B build_bench -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_C_COMPILER=$CC \
            -DBUILD_BENCHMARKS=ON -DBENCH_INCLUDE_BGL=ON -DCMAKE_BUILD_TYPE=Release
        continue-on-error: false

      - name: Build the Benchmarks
        run: |
          cmake --build build_bench/ -j$(nproc)
        continue-on-error: false

      - name: Execute the Smoke Test
        run: |
          ./build_bench/benchmarks/cpp-gl-bench \
            --benchmark_repetitions=1 --benchmark_display_aggregates_only=true \
            --bip-v 100 \
            --hg-bfs-e 100 --hg-bfs-esize 5
