name: clang++
on:
  push:
    branches:
      - '*'
    paths:
      - include/**
      - tests/**

jobs:
  build:
    name: Build and run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        env:
          CC:  clang-17
          CXX: clang++-17
        run: |
          cmake -B build -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_C_COMPILER=$CC
        continue-on-error: false

      - name: Build test executable
        run: |
          cd build && make
        continue-on-error: false

      - name: Run tests
        run: |
          ./build/test/run_tests
        continue-on-error: false
