name: g++
on:
  push:
    branches:
      - '*'
    paths:
      - .github/workflows/gpp.yaml
      - include/**
      - tests/**


jobs:
  build:
    name: Build and run tests
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        env:
          CC:  gcc-12
          CXX: g++-12
        run: |
          cmake -B build -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_C_COMPILER=$CC
        continue-on-error: false

      - name: Build test executable
        run: |
          cd build && make -j 4
        continue-on-error: false

      - name: Run tests
        run: |
          ./build/tests/run
