name: Licence
on:
  push:
    branches:
      - "*"
    paths:
      - .github/workflows/licence.yaml
      - scripts/common.py
      - scripts/check_licence.py
      - include/**

jobs:
  build:
    name: Test License Comments
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Validate Licence Comments
        shell: bash
        run: |
          python3 scripts/check_licence.py
